[project]
name = "ctae-pre-annotation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["polars", "ruff", "ty", "more-itertools", "lseval", "frozendict", "frozenlist"]

[tool.uv.sources]
lseval = { path = "/Users/etg/Repos/lseval", editable = true }